name: Unit Tests

on:
  push:
    branches: [ master ]
    paths: 
      - 'OBSControl/**'
      - 'OBSControlTests/**'
      - '.github/workflows/UnitTests.yml'
  pull_request:
    branches: [ master ]
    paths: 
      - 'OBSControl/**'
      - 'OBSControlTests/**'
      - '.github/workflows/UnitTests.yml'

jobs:
  tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: dotnet test --logger GitHubActions -p:DisableZipRelease=true -p:DisableCopyToPlugins=true -p:CIBuild=true
